src/backend/functionNode_webgl.js

As per #10 , added regex optimizer for the encode/decode 32 pairs

Adding encode32/decode32 pair optimization

---

demo/playground.css
demo/playground.html
demo/playground.js

Fully functioning benchmark demo : DONE!

Eugene #25 demo

---

src/backend/mode_gpu.js

Fix flatten performance for larger array sizes

---

README.md

@robertleeplummerjr PTAL. I added a TOC section too, is that cool?

Formatting and other fixes

---

src/backend/cpu/runner.js
src/backend/kernel-base.js
src/texture.js

@robertleeplummerjr PTAL.
I omitted some methods and parameters. Discuss here what those do and how they should be documented.

Internal Documentation: kernel-base

---

src/backend/cpu/function-builder.js
src/backend/cpu/function-node.js
src/backend/cpu/kernel.js
src/backend/cpu/runner.js
src/backend/function-builder-base.js
src/backend/function-node-base.js
src/backend/web-gl/function-builder.js
src/backend/web-gl/function-node.js
src/backend/web-gl/kernel.js
src/backend/web-gl/runner.js
src/backend/web-gl/validator-kernel.js

@robertleeplummerjr Just left with `kernel.js` for both `webGl` and `cpu`.

Internal Documentation: base classes, webgl, cpu

---

gulpfile.js
package.json
src/backend/cpu/function-builder.js
src/backend/cpu/function-node.js
src/backend/cpu/kernel.js
src/backend/cpu/runner.js
src/backend/function-builder-base.js
src/backend/function-node-base.js
src/backend/kernel-base.js
src/backend/runner-base.js
src/backend/web-gl/function-builder.js
src/backend/web-gl/function-node.js
src/backend/web-gl/kernel.js
src/backend/web-gl/runner.js
src/backend/web-gl/validator-kernel.js
src/core/gpu-core.js
src/core/gpu.js
src/core/texture.js
src/core/utils-core.js
src/core/utils.js
src/notes/js-native-class.js
src/notes/kernel-obj-format.js

@PicoCreator Your code was already upstream so I ran the task at my end and pushed the changes. Hope that's not an issue. :tada:

Gulp task to convert comments to JSDoc format

---

gulpfile.js
src/backend/cpu/function-builder.js
src/backend/cpu/function-node.js
src/backend/cpu/kernel.js
src/backend/cpu/runner.js
src/backend/function-builder-base.js
src/backend/function-node-base.js
src/backend/kernel-base.js
src/backend/runner-base.js
src/backend/web-gl/function-builder.js
src/backend/web-gl/function-node.js
src/backend/web-gl/kernel.js
src/backend/web-gl/runner.js
src/backend/web-gl/validator-kernel.js
src/core/gpu-core.js
src/core/gpu.js
src/core/texture.js
src/core/utils-core.js
src/core/utils.js
src/notes/js-native-class.js
src/notes/kernel-obj-format.js

Most(almost all) of the tags have been converted, next step is to purge NaturalDocs, and see how the final documentation looks and make the required changes. :tada:

Internal Documentation: Convert to JSDoc

---

gulpfile.js
src/backend/cpu/function-builder.js
src/backend/cpu/function-node.js
src/backend/cpu/kernel.js
src/backend/cpu/runner.js
src/backend/function-builder-base.js
src/backend/function-node-base.js
src/backend/kernel-base.js
src/backend/runner-base.js
src/backend/web-gl/function-builder.js
src/backend/web-gl/function-node.js
src/backend/web-gl/kernel.js
src/backend/web-gl/runner.js
src/backend/web-gl/validator-kernel.js
src/core/gpu-core.js
src/core/gpu.js
src/core/texture.js
src/core/utils-core.js
src/core/utils.js

@PicoCreator PTAL, Sir.
Next step is to change `ant build.xml` to incorporate `JSDoc`. (On a seperate branch.)

Comments have been converted. Docdash landing soon :rocket:

---

build.xml
jsdoc.json
src/backend/cpu/function-builder.js
src/backend/cpu/function-node.js
src/backend/cpu/kernel.js
src/backend/cpu/runner.js
src/backend/function-builder-base.js
src/backend/function-node-base.js
src/backend/kernel-base.js
src/backend/runner-base.js
src/backend/web-gl/function-builder.js
src/backend/web-gl/function-node.js
src/backend/web-gl/kernel.js
src/backend/web-gl/runner.js
src/backend/web-gl/validator-kernel.js
src/core/gpu.js
src/core/texture.js
src/core/utils.js

@robertleeplummerjr This is using [docdash](https://github.com/clenemt/docdash). As you pointed out in #110, we should change the theme color.
For that, we can either inject `CSS/JS`, or we can maintain our own copy of `docdash` and pull that everytime `setup-docs` is called.
We could fork the project to `gpujs` (parent organization) and I could change the color themes in that copy.(Though, that's my opinion.)
If you have any other idea, please share.

JSDoc is here

---

build.xml
gulpfile.js

CSS injection using gulp to modify docdash's theme

---

test/html/issues/116-multiple-kernels-run-again.html
test/html/test-all.html
test/src/issues/116-multiple-kernels-run-again.js

Unit test for #116

---

src/backend/function-node-base.js
test/html/test-all.html
test/src/issues/313-variable-lookup.js

fix #313 and add unit test

---

dist/backend/web-gl/kernel.js
test/issues/96-param-names.js

code review comments

---

package-lock.json
package.json
src/core/gpu.js
test/benchmark-faster.js
test/benchmark.js
test/index.js

Proof of concept work in progress to use headless-gl and node-canvas to provide 1:1 API support.

WIP Add headless gl for node support

---

src/index.d.ts

I've added one missing type annotation :)

Add missing type annotation

---

README.md

This PR adds a small note for Linux users, as there are some non-obvious dependencies which need to be installed in order for the build to succeed - and the error messages are  _singularly unhelpful_.
Note that there _may_ be additional packages missing from the list here, as I've run into some issues and opened #468.

README.md: Add Linux installation notes

---

src/index.d.ts

One more missing type annotation added.

missing type annotation

---

README.md

Updates README.md to remove reference to now removed playground and fixed broken logo link at the top. Issue #542

README link fixes

---

README.md

Update : Modify Typo in README.md

---

README.md

Matrix multiplication implemented using GPU.js + Angular
https://balramchavan.medium.com/using-gpu-js-in-angular-22674435a12b
https://ng-gpu.surge.sh/

Using GPU.js in Angular example
