README.md
Because of GPU.js's strict restrictions, the function passed to the kernel cannot have variable number of arguments passed to it.
Hence, either the `render` function should be called with a value or the function passed to the `createKernel` method should not accept any arguments. Because the function does not require any arguments, it's signature should not require any arguments as well.
=> Remove invalid function parameters.

src/backend/mode_gpu.js, test/html/android_encode32_test.html
I borrowed the float encoding/decoding code for my own project, but found a bug when testing on my Android's Chrome (Note 3 running Lollipop). Apparently it rounds rather than truncates when converting the RGBA vec4 to 4 unsigned ints. Running android_encode32_test.html on my phone gives:
```
0
-0.20000000298023224
-0.4000000059604645
-0.5999999642372131
-0.800000011920929
-4
-4.799999713897705
-5.599999904632568
-6.400000095367432
-7.199999809265137
-2
-2.1999998092651367
-2.3999998569488525
-2.5999999046325684
-2.799999952316284
```
when it should be more like (as it is on my laptop):
```
0
-0.20000000298023224
-0.4000000059604645
-0.6000000238418579
-0.800000011920929
-1
-1.2000000476837158
-1.399999976158142
-1.600000023841858
-1.8000000715255737
-2
-2.200000047683716 …
```
=> Fix Android Dragons Truncation Bug

package.json
gulp-rename was missing when I cloned the repo and tried to run locally.
=> Added missing gulp-rename dependency

src/utils.js
This is to make `gpu.supportWebgl()` return a boolean instead of a function.
=> fix(isWebgl): return a boolean

package.json
An empty string value for the "main" key in package.json prohibited imports(require) of the module. This PR fixes it.
=> Fixes npm modules to allow imports

src/backend/runner-base.js
As discussed.
Brief: The function check is being done inside `createKernel` method of class `GPU` ( [Function check inside gpu.js-line-78](https://github.com/gpujs/gpu.js/blob/develop/src/gpu.js#L78) ) and hence this check is redundant.
=> Removes redundant check in runner-base

src/core/gpu.js, src/core/utils-core.js
I'm using a old 2011 MacBook Air, with the `#ignore-gpu-blacklist` enabled on Chrome.
`WebGL2RenderingContext` is defined, however the Canvas doesn't support WebGL2 (`canvas.getContext('webgl2')` returns `null`).
These changes check if WebGL2 is supported on the canvas before selecting the `WebGL2Runner`.
=> Use WebGLRunner if canvas does not support WebGL2

src/core/utils-core.js, test/all.html, test/features/offscreen-canvas.js
These changes add support for OffscreenCanvas as discussed in #5.
Some browsers support it via flags: https://caniuse.com/#feat=offscreencanvas
Chrome Canary 70, appears to enable the flags or support  by default.
=> Add initial support for OffcreenCanvas

src/index.d.ts
Fix various TypeScript compile errors, all of which relate to implicit 'any' types in index.d.ts
=> fix: Implicit 'any' types

src/index.d.ts
fix: Missing parameter typings for the methods GPU.combineKernel and GPU.createKernelMap
=> fix: Missing parameter typings

bin/gpu-browser-core.js, bin/gpu-browser-core.min.js, bin/gpu-browser.js, bin/gpu-browser.min.js, src/backend/gl-kernel.js, test/features/return-arrays.js
The return-arrays.js tests are updated to have non-square output sizes and for each output to have a unique value.
I also renamed all variables (which I assume are supposed to be the same thing) to `xResultsMax`.
=> Fix return of >=2d arrays from GPU

dist/gpu-browser-core.js, dist/gpu-browser-core.min.js, dist/gpu-browser.js, dist/gpu-browser.min.js, gulpfile.js, package.json, src/browser.js, test/all.html
This allows downstream consumers to use GPU.js with requirejs,
d3-require, unpkg, jsdelivr, and probably some other systems. The main
changes:
- Set { standalone: 'UMD' } in browserify configuration. This makes it
publish a UMD build that exposes a 'UMD' export or global for
CommonJS, require, and AMD.
- Move bin/ to dist/, because these are properly distribution files
rather than binaries.
- Update tests to point to the dist/ version.
- Simplify browser.js to always export, because it is not the
recommended entry point for any browser.
- Add unpkg and jsdelivr fields to package.json so that those CDNs
automatically pick up on the right file when someone tries to include
from them.
=> Browser compatibility

src/backend/cpu/function-node.js, src/backend/web-gl/function-node.js
Sorry I don't have a repro steps, but after upgrading from v1 I'm getting `TypeError: this.astErrorOutput is not a constructor`.
=> Fix calls to FunctionNode.astErrorOutput, it's not a constructor

src/index.d.ts
Hi everyone, I noticed a little glitch in the TypeScript definition file. The definition of the `validateSettings()` function of the `Kernel` was missing a parameter definition. I guess this was a typo.
Please let me know if I should change something to make this pull request mergeable.
=> fix: define args of validateSettings() function

package.json
This pull request add a browser field to the package.json which points to the browser bundle.
It fixes #509.
=> add browser field to package.json

README.md
While following the documentation to load an image, there were some errors in the way `document.createElement` was called.
Furthermore it was unclear how to display the resulting output. (I know its already there, but in different section. It's nice when example can be copy/pasted and work end to end)
=> Improve examples for loading images via HTML

README.md
When I began using this package I struggled with the NPM Install process, as it has python dependencies in the rebuild process.
I did not realize that this package was automatically available via CDN
=> Add cdn links to readme

README.md
Hi. Tried to put into words what I learned about the reuse of textures; it should be helpful to anyone that like me wants to know how to induce texture reusage (like implementing any kind of self-referential equation without leaving the GPU).
=> Clarify pipeline mode allocation behavior

src/index.d.ts
```
render = new GPU.GPU({ mode: "gpu" })
render(image.data, 14 * Math.sin(Date.now() / 400))
```
In the above mentioned example since image data is of type Uint8ClampedArray & KernelVariable does not support the same hence gives type error
Ex: https://observablehq.com/@fil/image-to-gpu
=> Add support for type Uint8ClampedArray in KernelVariable

README.md
I've fixed semantically wrong Markdown link, and a typo (htt -> http).
=> fix: Fix typo and markdown in README

dist/gpu-browser-core.js, dist/gpu-browser.js, src/backend/cpu/kernel-string.js, src/backend/web-gl/kernel.js, src/backend/web-gl2/kernel.js
Fix for https://github.com/gpujs/gpu.js/issues/589
For an Angular 7.1 project, the prod build doesn't work, and it is caused by terser at the backend. Specifically the issue described here:
terser/terser#412
There are several examples in GPU.js of result.push('foo','bar','quux',) (note the trailing comma). These need to be removed. I have manually removed them in my local copy of the package (in dist/gpu-browser.js and dist/gpu-browser-core.js) and it builds. These seem to come from several of the source files in the back end. It should be an easy fix.
=> Remove trailing commas

package-lock.json, package.json
I noticed that gpu.js (and by extension brain.js) still use v4 of gl. v5 fixes some build issues users were having on macOS and linux, and upgrades node-gyp, which uses python 3 (saw a HackerNews thread about python 2.7 being a blocker for them installing brain.js)
Notes:
- Node 10 is no longer supported (it may or may not work). Node 12 is the oldest supported version (for now)
- Node 18 doesn't build properly, but that's not a regression. It should be resolved by the time 18 is LTS (September?)
- python 3 is used to build from source
- many build issues have been resolved (meaning lots of gpu.js/brain.js issues can be closed)
- prebuild-install supports npm 7
- by installing gl v5, the package-lock file was also updated, but it looks like it hasn't been updated in some time.
- some (13) …
=> Update gl to v5.x
